name: login_loveapp
description: Test use case for user login screen with mocked logic

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  freezed: ^1.1.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  provider: ^6.0.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed_annotation: ^1.1.0
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  mockito ^5.0.17

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/


